name: Docker Build XBPS container image

on:
  # manually
  workflow_dispatch:

env:
  GHCR_IMAGE: "ghcr.io/xhyrom/${{ github.event.repository.name }}"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: x86_64
            platform: linux/amd64
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: image
          platforms: ${{ matrix.config.platform }}
          outputs: type=image,name=${{ env.GHCR_IMAGE }}:${{ matrix.config.arch }},push=true
