name: Sync with upstream
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Sync with upstream
        run: |
          ./common/hypa/sync.sh

      - name: Commit changes
        run: |
          git add .
          git commit -m "build: sync with upstream $(date +'%Y-%m-%d') https://github.com/void-linux/void-packages/commit/$(git log upstream/master --pretty=format:'%h' -n 1)" || true
          git push || true
